DROP TABLE IF EXISTS animations;
DROP TABLE IF EXISTS guesses;
DROP TABLE IF EXISTS daily_puzzles;
DROP TABLE IF EXISTS pitch_profiles;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS divisions;
